### ISSUE TITLE
Missing assemblies in GetAllRelevantAssemblies

### ISSUE THREAD

**Issue by AndreasX10D** [3ds-cpe-emed/ws3dx-dotnet#54]
Line 113 needs to be changed in ws3dx-dotnet/ws3dx.core/serialization/registry/GlobalSchemaAttributeRegistry.cs.
The code line only returns loaded assemblies, not all assemblies.
This caused me to get errors as (for example) some masks are not identified correctly later in execution.
I modified the code to include all assemblies in the directory, and the error disappeared.

**Comment by 3ds-cpe-emed** [comment]
What is your use case? Maybe the context or how you are using it requires you do dynamically load assemblies. Normally if you just run the provided test cases the required assemblies se will be loaded automatically for you. 

Do you want to share the source code of your changes?

**Comment by AndreasX10D** [comment]
Hi,


In my scenario, I was running ModelService.Get<IModelRootServiceMask>(id) and it resulted in:

> System.ArgumentNullException
>   HResult=0x80004003
>   Message=Value cannot be null. (Parameter 'key')
>   Source=System.Private.CoreLib
>   StackTrace:
>    at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
>    at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
>    at System.Collections.Generic.Dictionary`2.ContainsKey(TKey key)
>    at ws3dx.core.serialization.CoreSchemaDeserializer`1.TypeIsSupportedGenericDictionaryClass(Type _type, Boolean _useCache) in C:\repos\XXX\YYY\ws3dx.core\serialization\CoreSchemaDeserializer.cs:line 147
>    at ws3dx.core.serialization.CoreSchemaDeserializer`1.DeserializeObjectFromClassImp(JsonElement _jsonObject, Type _classImpType) in C:\repos\XXX\YYY\ws3dx.core\serialization\CoreSchemaDeserializer.cs:line 290
>    at ws3dx.core.serialization.CoreSchemaDeserializer`1.DeserializeItem(JsonElement jsonElement, Type _type) in C:\repos\XXX\YYY\ws3dx.core\serialization\CoreSchemaDeserializer.cs:line 135
>    at ws3dx.core.serialization.MaskSchemaDeserializer`1.DeserializeElement(JsonElement _jsonElem, Type _deserializedElemType) in C:\repos\XXX\YYY\ws3dx.core\serialization\MaskSchemaDeserializer.cs:line 27
>    at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
>    at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)

After investigating, I could see that the ws3dx.dspfl.* assemblies was never loaded.

I added the following code block to resolve the problem:

```
// This method will only get the loaded assemblies, not all assemblies!
//Assembly[] assemblies = AppDomain.CurrentDomain.GetAssemblies();

List<Assembly> assemblies = AppDomain.CurrentDomain.GetAssemblies().ToList();
foreach (string dll in Directory.GetFiles(thisAssemblyPath, "*.dll"))
{
	try
	{
		Assembly assy = System.Reflection.Assembly.LoadFile(dll);
		if (!assemblies.Exists(x => x.FullName == assy.FullName))
			assemblies.Add(assy);

	}
	catch { }
}
```

I don't know why it didn't load the assemblies properly, but the above code solved the problem.

**Comment by 3ds-cpe-emed** [comment]
mmmhhh... are you using some dynamic way to refer to the return variables (e.g. `var ret = modelService.Get(id)` ... ) ?

If you have assigned the type to your return variable (e.g. `IModel ret = modelService.Get(id)` ) then C# should correctly handle the loading of all the dependent assemblies in memory. I cannot see any other reason why that is not happening in your case.

**Comment by 3ds-cpe-emed** [comment]
cannot reproduce
